---
- name: "Apply wakeonlan server configuration"
  hosts: raspberrypi
  become: true
  gather_facts: true
  roles:
    - common
    - netplan
    - cups
    - sane
    - scanservjs
    - wake_on_lan
    - AP
    - n8n_docker
