network:
  version: 2
  ethernets:
    eth0:
      addresses:
        - 192.168.1.203/24
      routes:
        - to: 0.0.0.0/0
          via: 192.168.1.1
      nameservers:
        addresses:
          - 8.8.8.8
          - 8.8.4.4
      wakeonlan: true
    wlan0:
      addresses:
        - 10.42.0.1/24  # Static IP for wlan0
      dhcp4: no
      dhcp6: no