- name: Install dnsmasq
  apt:
    name:
      - iptables-persistent
    state: present
    update_cache: yes
  
- name: Enable IP forwarding
  lineinfile:
    path: /etc/sysctl.conf
    regexp: '^#?net.ipv4.ip_forward='
    line: 'net.ipv4.ip_forward=1'
  notify: reload sysctl

- name: Configure NAT with iptables
  shell: |
    iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
    iptables -A FORWARD -i wlan0 -o eth0 -j ACCEPT
    iptables -A FORWARD -i eth0 -o wlan0 -m state --state RELATED,ESTABLISHED -j ACCEPT
  args:
    executable: /bin/bash
  notify: save iptables rules